### ISSUE TITLE
Server crashes when missiles explode

### ISSUE THREAD

**Issue by quantumtweaker** [BuiltBrokenModding/ICBM#108]
When firing any type of missile and the missile hits something and goes to explode, my server crashes out.

FML-Client-3.log: https://paste.ee/p/5lJMI

**Comment by DarkGuardsman** [comment]
java.lang.NoSuchFieldError: patternTab
	at mcp.mobius.waila.overlay.Tooltip.<init>(Tooltip.java:110)
	at mcp.mobius.waila.overlay.Tooltip.<init>(Tooltip.java:99)
	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:99)
	

Managed to replicate the issue by mistake. It does seem to be an issue inside Waila though I'm unsure why it is happening. From what I can tell some or all parts of mcp.mobius.waila.api.SpecialChars is failing to load. This could be due to a missing libary, java version, or other dependency. 

As this is an error on waila's side I'm closing the issue. Mainly due to the fact that ICBM in no way actually manipulates, uses, or interacts with Waila.

**Comment by DarkGuardsman** [comment]
As an additional note this seems to only happen with Tinkers Construct installed. Looking at the code I have locally for their project it is using an outdated Waila api file. If tinkers includes this file it could cause the issue,
