### ISSUE TITLE
Missile station allows invalid placement

### ISSUE THREAD

**Issue by DaMachinator** [BuiltBrokenModding/ICBM#130]
When you place the missile station it will allow you to place it in such a way that the top or bottom block does not place, leaving a two block missile station.

**Comment by DarkGuardsman** [comment]
So you are placing the missile crafting station on a wall. Then one of the blocks will go missing? Could be a failure in the collision check code on placement. Will look into it and get back to you. If you can in the mean time attempt to get a screenshot of the issue. This way I can confirm exactly what you are saying.

**Comment by DaMachinator** [comment]
Yes, I placed it on the wall - can it go on the floor? 

I "used" the item (to place) on the block adjacent to the floor, so the bottom block was missing.

I have screen capturing software, I'll make a video of what I noticed.

**Comment by DarkGuardsman** [comment]
Fixed in dev version not sure when a new build will be up

https://github.com/BuiltBrokenModding/ICBM/commit/a94a752687c16f60c957033cde3f54769c44939b

Additional Fix in VoltzEngine to help reduce this error in other multi-block structures
https://github.com/BuiltBrokenModding/VoltzEngine/commit/49da5d8a1ee3ad6138fffd05168a32adf76f31b7

**Comment by DaMachinator** [comment]
Yay! Sorry I never got the video, I captured it but things happened
