### ISSUE TITLE
Question about Warheads

### ISSUE THREAD

**Issue by jackbirkby** [BuiltBrokenModding/ICBM#143]
I'm pretty sure you'd already know about this but I figured I'd post to get an official response on the subject - warheads seem to have variable yield values that change every time the game is launched. Most of the time they are in the correct order (warhead>small warhead>micro warhead) however this isn't guaranteed, as several times I've launched and had massive yield micro warheads and much smaller standard warheads. 

Using antimatter as an example, micro warheads seem to mostly generate between values of 1.0m to 5.0m yield, Small warheads between 5.0m and 8.53m yield and standard warheads from 8.1m to 13.57m yield. This does not take into account anomalous values such as 1.0m standard warheads that sometimes appear for example.

My first question is is this a low priority bug for a much later release to touch on while you work on new features, or will it be fixed in the near future?

Secondly, can you give us an idea of the currently planned blast radii for each tier of explosive? (since each specialised payload varies within tiers, values for a standard TNT/antimatter explosion would be just fine as it gives an idea of what to expect for the others)

Also, I presume the ability to add the 3 current sizes of warhead to small and standard missiles (possibly rockets, although I haven't tested that myself) is just a side effect of the code leaning toward being more "bare-bones" for bug fixing purposes and ease of development at this stage. I don't mind at all as it gives me a chance to use the bigger warheads while the standard launcher is fixed!

Massive thumbs up to all you guys working on the mod, loving it so far despite its beta status and looking forward to future additions and development! (p.s. that AMS model is gorgeous, can't wait for it to recognise friendly missiles as I'll be all over it!)

**Comment by DarkGuardsman** [comment]
This bug should have been fixed in the last developer version. In which some core code in VoltzEngine was calculating the wrong yield values. I'll continue to look into it but the unit tests show nothing is wrong.

As well the warheads are designed to be variable through crafting, meaning no guaranteed tier size. The micro can be crafted with a single explosive, small 5 explosives, and standard 20 explosives. Each explosive has it's own size and a custom way of scaling the size. Most generally just add up the predicted volume of the explosive. Then use the new volume to calculate the expected yield, which is cached in memory. 

As for inserting different size warhead this is intended. The micro should only be able to fit the micro-missile. Small missile can accept the micro and small warhead. Standard can fit all 3 sizes though is a bit pointless. As each size of warhead is limited in both explosives and functionality.
