### ISSUE TITLE
Suggestion: Change AMS ammo behavior

### ISSUE THREAD

**Issue by TerdyTheTerd** [BuiltBrokenModding/ICBM#210]
I recently tested the "release" version of the mod, and one of the first things I noticed was just how op the ams is. It uses nuggets as ammo, ok not too bad, sets one up and fires a missile at it, realizes it has a range of 100 blocks horizontally and 200 vertically. Ok thats op. My suggestion is to add a config option so players can choose what should be the ammo, by use of unlocalized names so we can also use modded blocks, that way we can choose something more expensive, as a nuggest is as cheap as dirt. I also feel that the AMS should have greatly reduced range unless it is either 1) Powered by RF, EU or MJ where you can specify the range (to a limit) and it uses more energy/tick the larger the range or 2) Add in upgrades to the AMS that let you do things like faster shooting, larger range, more ammo slots ect.

**Comment by dmodoomsirius** [comment]
we do plan on having power support down the road. and as far as the ammo goes that is up to @DarkGuardsman.

**Comment by DarkGuardsman** [comment]
The current AMS turret is more or less just a temp solution. As people were constantly asking for a way to shoot down missiles. There are plans to do ammo, power, upgrades, and other restrictions. Including a need to add radar in order to make the AMS see the missile in time. As for the 100 block range, this is not that bad as the 1.6.4 version had a 300 block range. 

As well the AMS will be removed when I finish the sentry gun mod. Which will add 20+ different AntiMissile turrets including low-tech versions that barrel work and high-tech versions that always work. As well missiles will be getting upgrades down the road to bypass AMS systems more often. For example an ender engine to teleport, radar absorption hall to reduce detection, radar distribution to confuse AMS, and other upgrades.

**Comment by TerdyTheTerd** [comment]
Those plans sound amazing, seems like you already have the long road all planned so Ill close this
