### ISSUE TITLE
Open modular turrets support

### ISSUE THREAD

**Issue by jeg623** [BuiltBrokenModding/ICBM#228]
Open modular turrets are like the ICBM turrets from 1.6.4 and could act as a replacement as it offers a variety of guns and only need to make one of them act like flak turrets.

**Comment by DarkGuardsman** [comment]
I thought I commented on this already, no.... open modular turrets is its own mod that is not designed for PvP. Its more geared towards PvE gameplay and is limited compared to the older ICBM turret versions. I do plan to still work on the ICBM turret mod as part of a different mod. Especially since the code is very easy to update from the old 1.6.4 version. Which I will get to after I finish a lot of needed features in ICBM itself.
