### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by TheRandomLabs** [BuiltBrokenModding/ICBM#239]
When I launched a small missile and it landed, the server crashed with this crash log:
http://pastebin.com/1y41pdP9

**Comment by DarkGuardsman** [comment]
Looks like it was running client only code on the server. I should have time to fix the issue later this week once I'm done with finals.

**Comment by TheRandomLabs** [comment]
Just to save you the troulbe of tracking it down, at the bottom of com/builtbroken/icbm/content/blast/effect/BlastEnderBlocks.java, you had an if statement that checked if world.isRemote is false. If world.isRemote is false, then it's a server world.

**Comment by DarkGuardsman** [comment]
You mean https://github.com/BuiltBrokenModding/ICBM/blob/development/src/main/java/com/builtbroken/icbm/content/blast/effect/BlastEnderBlocks.java#L174

Right after you reported the bug I already looked at that line. There is nothing on that line, the entire class, or the packet it calls that should cause the issue. Which means I have to look into it more and most likely do some debug. Which I will get to tomorrow evening or Thursday as I will be done with my exams.

**Comment by TheRandomLabs** [comment]
Isn't that the file I sent you?
Anyway, remove the '!' and it should be fixed, because isRemote is true only for client worlds.

**Comment by DarkGuardsman** [comment]
!world.isRemote is the correct usage as I'm ensuring the code runs server side. That line generates a network packet that is sent to the client. Then the client itself renders the particle effect. If the packet is fired client side it will not work as the client does not contain the blast data to render the effect. 

The bug is not happening in the class itself but is being caused by a class loaded during that method call. Most likely it is actually https://github.com/BuiltBrokenModding/VoltzEngine/blob/development/src/main/scala/com/builtbroken/mc/core/network/packet/PacketSpawnParticleStream.java#L60 which is calling a client-side only method. The class loader may be loading the EntityFx.class because of the World.class references it in that method. 

You may be getting confused by the method name which notes to render effects for the blast. However, this method is only called server side and depends on the blast to sync with the client on it's own. It was originally fired on both sides when the blasts calculated on both the client and server. However, because of client ram issues the blasts only run on the server and then update the client as needed.

**Comment by TheRandomLabs** [comment]
Oh, sorry.

**Comment by DarkGuardsman** [comment]
Ok I just tested the issue and spotted the problem. I was looking at the wrong class and this is the actual packet class that was being used https://github.com/BuiltBrokenModding/VoltzEngine/blob/development/src/main/scala/com/builtbroken/mc/core/network/packet/PacketSpawnStream.java#L130
It references EntityFx code right on that line and the if statement bellow.
