### ISSUE TITLE
game crashes on world load

### ISSUE THREAD

**Issue by philip-stuckey** [BuiltBrokenModding/ICBM#268]
I made an new creative super-flat world and I put down an ICBM block and tried to open its UI, then my game crashed and now it crashes whenever I try to load that world

here is the log file with all of the juicy details
[crash-2017-03-04_15.29.22-server.txt](https://github.com/BuiltBrokenModding/ICBM/files/818920/crash-2017-03-04_15.29.22-server.txt)

I apologize if this is a duplicate or I am using  the wrong version of something
cheers

**Comment by DarkGuardsman** [comment]
No need to apologize, and yes you are using an old version. This issue was resolved in a newer version of VoltzEngine, all old versions should have been achieved on [Curse](https://minecraft.curseforge.com/projects/voltz-engine) to avoid this issue. I'll double check here later and push out a new recommended version if needed.

You are using: VoltzEngine{0.28.2.356}
Latest: [0.28.5b366](https://minecraft.curseforge.com/projects/voltz-engine/files/2386366)
Recommended: [0.28.5b363](https://minecraft.curseforge.com/projects/voltz-engine/files/2384229)

**Comment by philip-stuckey** [comment]
Thanks! its working now!
