### ISSUE TITLE
You can't remove missile from standart launcher any way except launch it

### ISSUE THREAD

**Issue by sliterok** [BuiltBrokenModding/ICBM#275]

**Comment by DarkGuardsman** [comment]
Intentional, the standard launcher and up are not designed to be feed by hand. That is why the track system was implemented in Assembly Line to move the missiles around. 

https://minecraft.curseforge.com/projects/assembly-line

https://www.youtube.com/watch?v=0FW03d9Xy_c

Right now, standard missiles are not fully supported by the system. However, it is planned to be implemented in the near future.
