### ISSUE TITLE
[Suggestion] EMP on Machines

### ISSUE THREAD

**Issue by Paralaxus** [BuiltBrokenModding/ICBM#290]
Hi.

My suggestion is that when a nuclear or EMP missile goes off, all machines that store power lose it when inside the affecting radius.

This used to work with mechanism machines in the Voltz pack.
I was wondering if it could work with the following mods:

Thermal Expansion,
Mechanism, 
GalactiCraft,
IndustrialCraft2,
MineFactory Reloaded.

**Comment by DarkGuardsman** [comment]
That is how they already work. EMP uses the Universal Power system to damage and drain energy from all tiles. Though it has some issues with RF tiles due to King setting up the API to limit power drain.

Nuke when added will just trigger an EMP as part of its layered design. It will also set off 20 other explosives types including heat waves, shock wave, plasma, atomisation, IR burst, Microwave burst, ION burst, etc.
