### ISSUE TITLE
Emp Grenades and a warning for Trackers

### ISSUE THREAD

**Issue by ClaytonRayG** [BuiltBrokenModding/ICBM#47]
I've always liked the idea of the emp having a grenade variant. Of course if deemed overpowered could be disabled in the configs like everything else.

Also, trackers need to have the ability to give a player a warning when they are being tracked. It causes people to be more careful when tracking others. They have to focus on others not paying attention. This would be toggleable in the config with the ability to make the message custom. 
For example: "Warning: Someone is tracking you!"

Also, I know it counts as a bug but emps working on RF based devices would be nice.

Also, possibly the ability to craft antimatters without resonant induction present?

**Comment by djoveryde** [comment]
Perhaps an emp room that kills trackers, like players build a chamber out of a particular block with an emp block that will fry it, random odd thought but means players can use it if they believe they have a tracker. (Imagine a decontamination room)

**Comment by DarkGuardsman** [comment]
How about instead EMP sealed room with an emp generator in the middle. This way we don't need to make new content to get the effect. Instead we use the blocks already planned to block EMPs to keep the pulse inside the room. Then just set off any normal emp to fry everything in the room.

**Comment by djoveryde** [comment]
Sounds good, regarding the tracker is there a way of placing a small blinking device on the player when they get tracked. That way it doesnt warn them but if they was to look in 3rd person they would see it on their body. Kinda like trackers in films perhaps. Then they can rush to the emp room and disable it.

**Comment by DarkGuardsman** [comment]
I could add some visuals as that was something we bounced around a few times. Since we would already be messing with the player render it shouldn't be an issue. Only problem is how easy we want to make it be seen.

I was also thinking of adding an item that could be picked up by the player. That would do the same exact thing but would require the player to remove it from their inventory. Could even make it were the item can camo as another item. For example look like an IC2 can of food until you go to eat it. In which you get back a can and a tracker that is beeping.
