### ISSUE TITLE
Startup Crash with resonant engine 3.3.0.401

### ISSUE THREAD

**Issue by Timorr** [BuiltBrokenModding/ICBM#59]
http://pastebin.com/3SJK2rkR

**Comment by dmodoomsirius** [comment]
You are using an outdated version of Resonant Engine. We are in the process of changing engines anyway.

**Comment by Timorr** [comment]
but it is the newest version on the page...

**Comment by DarkGuardsman** [comment]
Thought this might happen, its not that is outdated its that @calclavia removed a lot of code. Can't blame him as i no longer work on RE and ICBM no longer uses it. However, due to this change any ICBM version 2.3.0 and down will not function. What you can do is try to find an older RE version that works. If you can't then you have to wait until we get the new versions released.

**Comment by Timorr** [comment]
Thanks!
